//Define Fruit Object type with required properties like id, name, image, unit and price
type Fruit = {
    id: number;
    name: string;
    price: number;
    image: string;
    unit: string;
}
// Note:As per test requirement, Fruits API should be running on port 3000
function getFruits() {
    //Return the promise returned by the fetch() method
    fetch('http://localhost:3000/fruits')
        .then((responce) => {
            if (responce.ok) {
                return responce.json();
            }
            else {
                throw new Error('Failed to fetch fruits');
            }
        })
        //Successful promise callback function should convert the response body text to json object and return the promise as result.
        .then(data => transform(data))
        .catch(error => {
            console.error('Failed to fetch fruits', error);
        });

    //Returned successful promise callback should call `transform()` method by passing the json object as argument
}

//Inside transform() function, iterate the json data passed as parameter.
//Then transform each fruit to transformedFruit object that mirrors Fruit type 
function transform(fruits: Fruit[]) {
    //call showFruit() function for each transformedFruit object
    const transformedFruits: Fruit[] = [];
    for (let i = 0; i < fruits.length; i++) {
        const fruit = fruits[i];
        const transformedFruit: Fruit = {
            id: fruit.id,
            name: fruit.name,
            image: fruit.image,
            unit: fruit.unit,
            price: fruit.price
        };
        transformedFruits.push(transformedFruit);
        showFruit(transformedFruit);
    }
}

//Inside showFruit() function, pass transformedFruit object as parameter
function showFruit(fruit: Fruit) {
    //display each transformedFruit as card by creating HTML code as string and appending it to the div container
    const container = document.getElementById('fruits-container'); // Replace 'fruits-container' with the actual ID of the <div> container element

    const fruitCard = `
    <div class="card">
      <img src="${fruit.image}" alt="${fruit.name}" class="card-img-top">
      <div class="card-body">
        <h5 class="card-title">${fruit.name}</h5>
        <p class="card-text">Price: ${fruit.price}</p>
      </div>
    </div>
  `;

    container.innerHTML += fruitCard;
}

//compiler error for "module" will be resolved once node_modules folder is generated by giving 'npm install' command in the terminal
// do not delete the code given below, it is written to export the functions to be tested
module.exports = {
    getFruits
}
